[package]
name = "bequeath"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
softbuffer = "0.3.1"
tiny-skia = "0.11.1"
winit = "0.28.6"
